var rule = {
  title: '唐人街影视',
  host: 'https://trjyingshi.com',
  searchUrl: '/index.php/vod/search/page/fypage/wd/**.html',
  url: '/index.php/vod/show/id/fyclass/page/fypage.html',
  headers: {
    'User-Agent': 'MOBILE_UA',
  },
  timeout: 5000,
  searchable: 2,
  quickSearch: 0,
  filterable: 0,
  class_parse: 'body&&.hl-nav li:lt(6);a&&Text;a&&href;/id/(\\d+).html',
  limit: 40,
  play_parse: true,
  lazy: '',
  推荐: '.hl-vod-list;li;*;*;*;*',
  double: true,
  一级: '.hl-vod-list&&.hl-list-item;a&&title;a&&data-original;.remarks&&Text;a&&href',
  二级: {
    title: 'h2&&Text;.hl-text-conch&&Text',
    img: '.hl-lazy&&data-original',
    desc: '.hl-text-conch:eq(1)&&Text;.hl-col-xs-12.hl-col-sm-4--em&&Text;.hl-col-xs-12.hl-col-sm-4--em:eq(1)&&Text;.hl-full-box li:eq(2)--em&&Text;.hl-full-box li:eq(3)--em&&Text',
    content: '.hl-content-text&&Text',
    tabs: '.hl-tabs&&a',
    lists: '.hl-plays-list:eq(#id)&&li',
  },
  搜索: '.hl-list-item;*;*;*;*',
  }